name: Code Coverage 
on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
    - name: Jacoco Report
      run: mvn -B clean package jacoco:report
    - name: Coveralls Report
      run: mvn -B coveralls:report --define repoToken=${{secrets.COVERALLS_SECRET}}
